url: http://www.geoworx.io/
baseurl: /

# Site settings
title: GeoWorx
email: mallika@geoworx.io
description: "GeoWorx is the leading software and service provider for Geological surveying, monitoring, and management."


# Team names, titles and social links
people:
- name: Mallika Vemuri
  pic: 1
  position: Founder, and CEO
  social:
    - title: twitter
      url: http://www.twitter.com/geoworx
    - title: facebook
      url: http://www.facebook.com/geoworx


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/geoworx
  - title: facebook
    url: http://www.facebook.com/geoworx

# Postal address (add as many lines as necessary)
address:
  - line: TBD
  - line: TBD

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman